In [ ]:
import pandas as pd
import matplotlib.pyplot as plt


df_vendas = pd.read_csv('vendas.csv')

In [5]:
df_vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   data            100 non-null    object
 1   produto         100 non-null    object
 2   categoria       100 non-null    object
 3   quantidade      100 non-null    int64
 4   preco_unitario  100 non-null    int64
 5   cliente         100 non-null    object
 6   regiao          100 non-null    object
dtypes: int64(2), object(5)
memory usage: 5.6+ KB

In [8]:
df_vendas.head()

,data,produto,categoria,quantidade,preco_unitario,cliente,regiao
0,2025-12-09,Headset G,Periféricos,1,2759,Fernanda,Sudeste
1,2025-03-12,Armário P,Móveis,2,4516,Rafael,Norte
2,2025-11-24,Mesa Escritório N,Móveis,1,4347,Rafael,Sudeste
3,2025-09-14,Tênis T,Vestuário,3,3046,Ana,Norte
4,2025-08-03,Boné V,Vestuário,2,4453,Bruno,Centro-Oeste

In [12]:
df_vendas.shape[0]

100

In [ ]:
df_vendas["Faturamento"]= df_vendas["preco_unitario"].sum()
print(df_vendas["preco_unitario"].sum())

276361

In [21]:
Filtro = df_vendas[df_vendas["categoria"].str.contains("Eletrônicos")] 
print(Filtro)

          data     produto    categoria  quantidade  preco_unitario   cliente  \
5   2025-07-24    Tablet D  Eletrônicos           2            4893  Fernanda
6   2025-05-20   Monitor B  Eletrônicos           1            3060     Lucas
9   2025-06-01   Celular A  Eletrônicos           3             516      João
10  2025-04-22   Celular A  Eletrônicos           2            1018  Fernanda
13  2025-11-24  Notebook X  Eletrônicos           1            2670       Ana
14  2025-05-30    Tablet D  Eletrônicos           4            2575     Maria
15  2025-09-19  Notebook X  Eletrônicos           2            2778    Rafael
27  2025-01-30  Notebook X  Eletrônicos           5            1006     Lucas
32  2025-07-07    Tablet D  Eletrônicos           2            2533    Camila
33  2025-11-20  Notebook X  Eletrônicos           4            3998     Pedro
36  2025-08-01      Fone C  Eletrônicos           5            2433     Pedro
41  2025-08-06      Fone C  Eletrônicos           5             246    Rafael
44  2025-05-25   Monitor B  Eletrônicos           2            3607     Lucas
49  2025-07-05      Fone C  Eletrônicos           4            2864  Fernanda
54  2025-04-01      Fone C  Eletrônicos           2            4350     Lucas
55  2025-04-09   Celular A  Eletrônicos           3            4362     Pedro
60  2025-10-05   Celular A  Eletrônicos           2            2742     Pedro
62  2025-11-29      Fone C  Eletrônicos           5            2798     Lucas
71  2025-10-12    Tablet D  Eletrônicos           2            4147      João
73  2025-08-15   Monitor B  Eletrônicos           5            3644     Pedro
76  2025-03-19   Celular A  Eletrônicos           5             922     Lucas
80  2025-03-16  Notebook X  Eletrônicos           3            4518    Rafael
83  2025-11-13      Fone C  Eletrônicos           5            4939    Rafael
85  2025-03-18  Notebook X  Eletrônicos           1            4603       Ana
90  2025-08-26   Monitor B  Eletrônicos           2            2718     Carla
91  2025-01-04  Notebook X  Eletrônicos           1            1612     Pedro
96  2025-10-16   Celular A  Eletrônicos           1            2046     Carla
97  2025-03-15   Celular A  Eletrônicos           5            4390     Carla

          regiao  Faturamento
5        Sudeste       276361
6            Sul       276361
9   Centro-Oeste       276361
10      Nordeste       276361
13           Sul       276361
14      Nordeste       276361
15         Norte       276361
27       Sudeste       276361
32           Sul       276361
33      Nordeste       276361
36           Sul       276361
41       Sudeste       276361
44           Sul       276361
49       Sudeste       276361
54  Centro-Oeste       276361
55         Norte       276361
60         Norte       276361
62         Norte       276361
71           Sul       276361
73       Sudeste       276361
76           Sul       276361
80           Sul       276361
83  Centro-Oeste       276361
85  Centro-Oeste       276361
90       Sudeste       276361
91      Nordeste       276361
96           Sul       276361
97      Nordeste       276361

In [25]:
df_vendas.sort_values(by='quantidade')

,data,produto,categoria,quantidade,preco_unitario,cliente,regiao,Faturamento
0,2025-12-09,Headset G,Periféricos,1,2759,Fernanda,Sudeste,276361
2,2025-11-24,Mesa Escritório N,Móveis,1,4347,Rafael,Sudeste,276361
6,2025-05-20,Monitor B,Eletrônicos,1,3060,Lucas,Sul,276361
11,2025-07-10,Tênis T,Vestuário,1,4967,João,Sudeste,276361
13,2025-11-24,Notebook X,Eletrônicos,1,2670,Ana,Sul,276361
...,...,...,...,...,...,...,...,...
73,2025-08-15,Monitor B,Eletrônicos,5,3644,Pedro,Sudeste,276361
83,2025-11-13,Fone C,Eletrônicos,5,4939,Rafael,Centro-Oeste,276361
64,2025-08-20,Webcam H,Periféricos,5,2022,Bruno,Sudeste,276361
97,2025-03-15,Celular A,Eletrônicos,5,4390,Carla,Nordeste,276361
98,2025-02-07,Calça U,Vestuário,5,2472,Rafael,Norte,276361

In [26]:
df_vendas['regiao'].value_counts()

regiao
Sudeste         27
Sul             22
Norte           20
Nordeste        16
Centro-Oeste    15
Name: count, dtype: int64